### ISSUE TITLE
Search leaking query with GET

### ISSUE THREAD

**Issue by jmcr412** [roteKlaue/firefox-startpage-search-extension#2]
The HTTP method is always GET and its leaking the search query terms. It should be using POST instead.
![leak](https://github.com/user-attachments/assets/3898273f-600d-4be5-b724-86c18938a3c5)

**Comment by roteKlaue** [comment]
Unfortunately, there isn't much that can be done about this specific issue due to the way most search engines operate. As you've noticed, even the default search engines in Firefox typically use the HTTP GET method, which includes the search terms in the URL.

The extension in question is designed to be simple and avoid including potentially risky JavaScript. Changing the method to POST would likely require additional JavaScript, which goes against the purpose of this extension.
